### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by zr950624** [Dobigthing666/Squirrel#2]

**Comment by Kalpesh-18** [comment]
I would like to work on it, if the issue is still in progress

**Comment by Changochen** [comment]
@zr950624

**Comment by zr950624** [comment]
> I would like to work on it, if the issue is still in progress

Sure, appreciate your participation in our project!
I already finish the dockerfile for MySQL, PostgreSQL, and MariaDB. If you could help with SQLite, it would be great!

**Comment by Kalpesh-18** [comment]
Yes sure I would do that

**Comment by Kalpesh-18** [comment]
Have you added the dockerfiles to the repo?

**Comment by zr950624** [comment]
> Have you added the dockerfiles to the repo?
I'm working on the `update_docker` branch, and you can see my commit there.

**Comment by Kalpesh-18** [comment]
Okay cool I would add the dockerfile for sqlite

**Comment by Kalpesh-18** [comment]
![image](https://user-images.githubusercontent.com/69343990/206905625-6bca19c7-09e1-4d51-8519-0dff79d42053.png)
Getting this error while building the docker image

**Comment by Kalpesh-18** [comment]
Hey can you please check #14 and let me know if any changes are required

**Comment by Kalpesh-18** [comment]
Thank you @zr950624  @Changochen , learnt a lot from this
